### ISSUE TITLE
Tutorial Video

### ISSUE THREAD

**Issue by Zusyaku** [BotolMehedi/braje#1]
Pld Teach how to use and get cookie

**Comment by BotolMehedi** [comment]
@Zusyaku

1.Use Fake Account
2.Use Kiwi Browser (Search On Play Store)
3.Use EditThisCookie Extension (Search on Chrome Extension Store)

Login Your Fake Facebook Account on Kiwi Browser. After Successfully Logged in Click On EditThisCookie extension. Copy Your Cookie.
